### ISSUE TITLE
Error: Stripe.js token was not passed! Report this message to the site administrator.(ext  ver. 1.9.1)

### ISSUE THREAD

**Issue by seajaee** [drastik/com.drastikbydesign.stripe#76]
@drastik I am getting this error [Stripe.js token was not passed! Report this message to the site administrator.] when using the Stripe processor with a real credit card number as well as a test credit card number on a live contribution page. Also, I don't know how to write code. :(

CiviCRM 4.4.5
Wordpress 3.9.3
Stripe Extension 1.9.1

**Comment by EranSch** [comment]
@drastik I suspect this is due to the issue noted on #75 -- where the `stripe-payment-form` class is not longer getting applied correctly.

**Comment by andywozhere** [comment]
Same issue for me I'm afraid. 

CiviCRM 4.5.6
Wordpress 4.1.1
Stripe Extension 1.9.1

**Comment by EranSch** [comment]
@andywozhere Before you submit the form, do you see any errors in your browser's JS console?

If you're using Chrome, be sure to check 'Preserve Log' so the console doesn't clear out after each each page load. I'm sure there's an equivalent in all the others....

![image](https://cloud.githubusercontent.com/assets/1479206/6394029/a9ecd544-bd9c-11e4-90d7-1a02bafd2839.png)

**Comment by andywozhere** [comment]
@Swingline0 Yes there are a few Javascript errors. It looks like it is omething to do with JQuery. Errors as follow:

Two errors on Common.js line 196
Uncaught TypeError: Cannot read property 'defaults' of undefined and (anonymous function)

``` javascript
// Theme classes for unattached elements
  $.fn.select2.defaults.dropdownCssClass = $.ui.dialog.prototype.options.dialogClass = 'crm-container';
us function)
```

(anonymous function) error on Common.js line 1077

``` javascript
})(jQuery, _);
```

Also :

Two errors on en_GB.js line 14
Uncaught TypeError: Cannot read property 'defaults' of undefined and (anonymous function)

``` javascript
CRM.formatMoney('init', "\u20ac 1,234.56");
```

(anonymous function) error on en_GB.js line 73

``` javascript
})(jQuery);
```

**Comment by andywozhere** [comment]
@Swingline0  Sorry those were after I submitted the form. Before I submitted the form I am told that the file at /wp-content/plugins/files/civicrm/custom_ext/com.drastikbydesign.stripe/js/civicrm_stripe.js?r=GoZZa  cannot be found.

**Comment by Upperholme** [comment]
And presumably that file does exist on that path in your install?

**Comment by andywozhere** [comment]
@Upperholme yep

**Comment by andywozhere** [comment]
@Upperholme @Swingline0 Solved (for me anyway). Incorrect resource URL. For me the resource URL was 

 /wp-content/plugins/files/civicrm/custom_ext

**Comment by drastik** [comment]
@andywozhere Thanks for the update!

Is this where CiviCRM puts extensions by default in WP?  Or is that a directory you set up?

**Comment by andywozhere** [comment]
@drastik You have to set it up there, but it is the folder recommended on [http://wiki.civicrm.org/confluence/display/CRMDOC/Extensions](http://wiki.civicrm.org/confluence/display/CRMDOC/Extensions). One concern I had was that the URL is written to https://domain.org//wp-content/plugins/files/civicrm/custom_ext which doesn't feel quite right... but it seems to work anyway!

**Comment by drastik** [comment]
@andywozhere Right, yes it gets re-written with domain name in there.

You can fix it now, (removing the extra /) I've seen some versions of Civi are doing this.

**Comment by MicahStevens** [comment]
I'm getting this too, trying to troubleshoot. I'm using:
CiviCRM 4.6.2
Wordpress 4.1.1

No Javascript errors, I fill out the form and I see the variable being passed from the form: 

```
------WebKitFormBoundaryAc0VWeX4HO8C4Jkw
Content-Disposition: form-data; name="stripe_token"


```

I don't see any XHR requests going to stripe at all, this is likely the problem. The create customer api call, or whatever this plugin is using isn't working. 

I'll keep troubleshooting, I'll update here if I find out anything interesting.

**Comment by MicahStevens** [comment]
Did some more in depth debugging - It appears in chrome at least, if you also enable the pay by check option in your contribution form the detection of whether you're paying by credit card or not isn't working. This part in particular: 

```
 // Handle multiple payment options and Stripe not being chosen.
      if ($form.find(".crm-section.payment_processor-section").length > 0) {
        if (!($form.find('input[name="hidden_processor"]').length > 0)) {
          return true;
        }
      }
```

My quick fix was to disable pay by check, since we don't need that right away, but I'll work on a pull request to update this code to make it work. 

Hope this helps!

**Comment by richardsplayground** [comment]
Same issue for me on : 
- CiviCRM 4.6.2
- Drupal 7.37
- Extension version 1.9.1 pulled from github on May 14ish

I get the error in two circumstances:
1) When multiple payment processors are allowed for an event.  For example, PayPal and Stripe.
2) When the "pay later" option is allowed on an event registration.

No errors appear in the Javascript console.

I was testing in Chrome as well.

Thanks @MicahStevens for your suggested quick fix.  I took the route of for now disabling pay later and PayPal.  Long term that won't work for us unfortunately.

**Comment by highfalutin** [comment]
Same issue here, on:
- CiviCRM 4.5.8
- Drupal 7.36
- Extension version 1.9.1, pulled today, May 18

I get the error on one contrib page, but not on another. The differences that I can see are:

|  | Error | No error |
| --- | --- | --- |
| Financial type | membership | donation |
| Uses price set | yes | no |
| Confirmation page | no | yes |
| Start date | in the past | null |
| Pay later | disabled | disabled |

I don't know if any of these are a clue to what's causing the problem.

No JS errors in the browser console. (Firefox)

Both pages are error-free with extension version 1.7. I was testing the newer version out of the hope that it would help us with recurring contributions, which have been a problem.

**Comment by laryn** [comment]
I can confirm the same on a new install from the zip file Github provides (extension 4.6-dev, listed in info.xml as v.1.9.1), on Drupal 7.36 with CiviCRM 4.6.3. (With or without the confirmation page, the same result -- only the error appears after the confirmation page is submitted if that page is enabled, otherwise immediately upon contribution page form submission).

The key factor seems to be the Pay Later option (it works if it is not enabled). I have not tested with a second payment processor option.

**Comment by highfalutin** [comment]
Unfortunately the Pay Later option does not seem to be the culprit in my
case.

**Comment by twbrooks101** [comment]
I've been having the same issue. As long as the "pay later" option is enabled, it's throwing the "Stripe.js token was not passed!" error. Once I removed that option, Stripe processed a live payment just fine.

Wordpress 4.2.2
Civicrm 4.6.2
Fruitful Theme

**Comment by enricospada** [comment]
I'm having the same issue as well. I turned off the Pay Later option, which prevents the error from appearing but also does not process the contribution (just refreshes the page with a blank form, or, if Confirmation Page is enabled, returns user back to the blank form).

Wordpress 4.2.2
Civicrm 4.6.3

EDIT:
I managed to install the 4.6dev branch, and, after disabling both Pay Later AND any other payment processor, it worked, same as @richardsplayground and @MicahStevens.

**Comment by mattwire** [comment]
I get this issue, drupal 7.39, civicrm 4.6.8.  No other payment processors enabled, no pay later.
The following pull request fixes it for me and seems to allow other payment processors/pay later to be enabled if required: https://github.com/drastik/com.drastikbydesign.stripe/pull/95

**Comment by bjendres** [comment]
We had the same issues as described above, Drupal 7.39, CiviCRM 4.6.8, pay_later enabled.

Our "hotfix" https://github.com/drastik/com.drastikbydesign.stripe/pull/97 patching [civicrm_stripe.js](https://patch-diff.githubusercontent.com/raw/drastik/com.drastikbydesign.stripe/pull/97.patch) did the trick, STRIPE's working perfectly now. I am, however, not quite sure what this bit of code was intended for in the first place.

**Comment by jmcclelland** [comment]
Same issue - drupal 7.39, civicrm 4.6.8 pay later enabled. The pull request in #97 did not work, but disabling pay later did work.

**Comment by jmcclelland** [comment]
There seem to be a few different reasons why people are getting this error. For the "Pay Later" reason - I think i fixed it with this pull request: https://github.com/drastik/com.drastikbydesign.stripe/pull/99

CiviCRM has changed the availability of the hidden_processor field in 4.6 - so that would explain why it works in 4.5 and not in 4.6 (see https://issues.civicrm.org/jira/browse/CRM-15743)

**Comment by mecachisenros** [comment]
I'm having the same issue as well, I'm not quite sure on how to start debugging.

CiviCRM - 4.6.4/4.6.8
Wordpress - 4.3.1
Stripe Payment Processor 1.9.2

I've tried with the default Twenty Fifteen theme, clean Wordpress and CiviCRM install, no extra plugins or extensions. 
Extensions Resources URL: http://www.site.com/dev/wp-content/plugins/files/civicrm/extensions/ (seems to be correct)
No additional payment processors and no 'Pay Later', trying to make payments for Events.

Result: 

> Sorry but we are not able to provide this at the moment.
> Stripe.js token was not passed! Report this message to the site administrator.

Backtrace:

```
#0 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(360): CRM_Core_Error::backtrace()
#1 /var/www/site/public_html/dev/wp-content/plugins/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/CRM/Core/Payment/Stripe.php(295): CRM_Core_Error::fatal("Stripe.js token was not passed!  Report this message to the site administrator.")
#2 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Event/Form/Registration/Confirm.php(619): CRM_Core_Payment_Stripe->doDirectPayment((Array:57))
#3 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(345): CRM_Event_Form_Registration_Confirm->postProcess()
#4 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(164): CRM_Core_Form->mainProcess()
#5 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Event_Form_Registration_Confirm), "next", "Next")
#6 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Event_Form_Registration_Confirm), "next")
#7 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Event_Form_Registration_Confirm), "next")
#8 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("next")
#9 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(312): CRM_Core_Controller->run((Array:3), NULL)
#10 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:15))
#11 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#12 /var/www/site/public_html/dev/wp-content/plugins/civicrm/civicrm.php(1189): CRM_Core_Invoke::invoke((Array:3))
#13 /var/www/site/public_html/dev/wp-content/plugins/civicrm/includes/civicrm.basepage.php(134): CiviCRM_For_WordPress->invoke()
#14 [internal function](): CiviCRM_For_WordPress_Basepage->basepage_handler(Object(WP))
#15 /var/www/site/public_html/dev/wp-includes/plugin.php(579): call_user_func_array((Array:2), (Array:1))
#16 /var/www/site/public_html/dev/wp-includes/class-wp.php(633): do_action_ref_array("wp", (Array:1))
#17 /var/www/site/public_html/dev/wp-includes/functions.php(886): WP->main("")
#18 /var/www/site/public_html/dev/wp-blog-header.php(14): wp()
#19 /var/www/site/public_html/dev/index.php(17): require("/var/www/site/public_html/dev/wp-blog-header.php")
#20 {main}
```

I'm not a developer but if I could help in anyway please let me know, I have a development environment ready for testing.

**Comment by mattwire** [comment]
Please test the latest version.  I believe it is fixed following this pull request: https://github.com/drastik/com.drastikbydesign.stripe/pull/102

**Comment by mecachisenros** [comment]
@mattwire I've tested the latest version, with the latest fix applied. The error above is with the latest version, tested a couple of hours ago.

**Comment by jmcclelland** [comment]
After a lot of trial and error I've created two reproducible ways to trigger this problem.

Setup: Event with Stripe payment processor and pay later option.

Scenario one: Fill out everything, but don't choose either the Stripe payment processor or the pay later option. Hit submit. Page reloads with CiviCRM error message about how you need to select a payment processor. Select stripe and hit submit again.  Fails.
Scenario two: Fill out everything except one required field. Choose Pay Later option. Hit submit. You get a CiviCRM error about missing field. Fill it in - and then change your mind and choose Stripe as the payment processor. Hit submit. Fails.

The reason both failures is the same:
- When reloading the page after an error - CiviCRM does not populate the _paymentProcessors property of the form. See Contribute_Form_Contribution_Main::preProcessPaymentOptions() - when the form has _submitValues set - it will only populate _paymentProcessors with the selected payment processor. But in both scenarios, Stripe is not chosen as the selected payment processor.
- stripe_civicrm_buildForm() is responsible for inserting the javascript code to create the stripe token. However, it is only triggered if _paymentProcessors is populated with a stripe payment processor.
- There is a fallback - if you click on the Stripe payment processor - the civicrm_stripe.js is injected (which causes Stripe to complain about being injected more than once). However, that doesn't solve the problem - since the code we need injected is wrapped in  $(document).ready(function(). Since the page is already loaded - this doesn't seem to be applied.

I'm not sure what the best approach is. Maybe some modification to the code that is injected when you click the stripe payment processor option? It could check to see if it has already been injected and not proceed if it has. However, if it hasn't been injected, perhaps it could run outside the ready() function??

@mecachisenros is stripe the default payment process on your system. I think we would similar errors to what I have experienced if do not have stripe set as the default option.

**Comment by mecachisenros** [comment]
@jmcclelland the tests I made, Stripe Processor was the only payment processor (also the default one), Pay Later disabled, filled in all required fields (ie Contact details from Profile, and Billing Address), no extension installed apart from Stripe. 
This morning I tested @systopia's fork (ref #97) which seems to fix this issue, the test was in the same environment (no extensions, no Pay later, no additional payment processor) the payment was processed successfully, couldn't process the payment in test mode though, but live payments seem to work.
Tomorrow morning I will test Systopia's fix with PayPal enabled and Pay Later and  I will report back.
I will try having a look at their fix, but as I said, not a developer, just some basic JavaScript knowledge, willing to help though.

**Comment by jmcclelland** [comment]
I just tried a new pull requests to address the problems I've experienced. It involves some re-factoring  to simplify the code (I hope):

https://github.com/drastik/com.drastikbydesign.stripe/pull/105

**Comment by rohankatkar** [comment]
Hi @drastik ,
I have clone the extension from here:  https://github.com/drastik/com.drastikbydesign.stripe (version-1.9.2)
and having following config:
 -- wordpress version: 4.2
 -- civicrm version: 4.6.2
 -- stripe: cloned from above link.

Previously, I had a issue related to Stripe.js token i.e token was not getting generated correctly.
But, I made patch for it, now there is issue related to Stripe.js is resolved and token is getting generate properly.
Following is the patch link to resolve 'Stripe.js token' error for (1.9.2): https://gist.github.com/rohankatkar/f30b16d98a75e828aa43

Now, I am having new issue related create_customer case.  
Following issue is getting when clicked on 'make contribution': 
"Error Oops! Looks like there was an error. Payment Response:"
and in response, Error type, error code and error message getting blank.

I have done some workaround for cases mentioned in CRM/Core/Payment/Stripe.php. The issue is getting occurred from the first case i.e "create_customer".
In 'create_customer' case, Stripe_Customer::create() function is used.
I thinnk, this issue is getting because of $apiKey parameter passed in Stripe_Customer::create() function. 

Because when I debugged in create() functon, parameter "$apiKey" is getting empty. I passed hard-coded $apiKey key as second parameter in switch case.
Is the $apiKey is already set globally anywhere? or second parameter i.e "$apiKey" is missing from all cases?

I have tried by passing apiKey as hard-coded as second parameter for 'create_customer' case. But still getting same eror


Can you please guide issue 'create_customer' case?

**Comment by rohankatkar** [comment]
Hi @drastik,

I am having issue with PayPal payment processor.  I have configured the Stripe on website with PayPal and pay-later option. Stripe is configured as defualt payment processor. Pay later and stripe is working fine. But now issue is, while submitting contribution with PayPal, its giving me an error:
"Error: Missing required param: number." which was getting occured previously in case of stripe.

The other scenario is, when there is none of the payment processor is set as default, then Paypal works fine and stripe gets break or is there any conflict when we configured PayPal and Stripe together? 

Any idea why this is happenning?

**Comment by drastik** [comment]
@rohankatkar,

Yes, a few are reporting that there is an issue when using multiple payment processors including Stripe.

**Comment by zeigerpuppy** [comment]
I'm also having this problem with the latest version of the stripe plugin pulled from github.
I have disabled other payment processors and pay later.
Wordpress 4.2.2 (Debian)
Stripe Payment Processor 1.9.2 
CiviCRM 4.6.4

Just wanted to make sure my settings are right too:
extension URL: https://mysite.com/wp-content/plugins/files/civicrm/custom_ext
Stripe payment URL: https://api.stripe.com/v2
Webhook https://mysite.com/?page=CiviCRM&q=civicrm/stripe/webhook

**Comment by hetclub** [comment]
I have exactly the same experience as rohankatkar  above.  I removed the Pay Later option, and have PayPal and Stripe.  When PayPal is default and Stripe is selected, I get the full screen error as above.  When Paypal is selected and Stripe is default, I get the "number" error as above.  It appears that which ever default is selected, triggers some behavior that CiviCRM requires the other processor to have because the error is happening at exactly the same point where they are different.  With Stripe as default, it requires the entry of a card number for Paypal, when Paypal is default, Stripe is failing when you would be forwarded to Paypal's website.  Is there some code that is run based on the default regardless of the payment processor?
Joomla 3.4.5
Stripe 1.9.1
CiviCRM 4.6.10

**Comment by hetclub** [comment]
So one additional comment.  If I remove any payment processor as the default, then I get the same result as if Paypal were the default - full screen error:

0 - <div id="crm-container" class="crm-container" lang="en" xml:lang="en"> <style type="text/css" media="screen"> @import url(/administrator/components/com_civicrm/civicrm/css/civicrm.css); @import url(/administrator/components/com_civicrm/civicrm/bower_components/jquery-ui/themes/smoothness/jquery-ui.min.css); </style> <div class="messages status no-popup"> <div class="icon red-icon ui-icon-alert"></div> <span class="status-fatal">Sorry but we are not able to provide this at the moment.</span> <div class="crm-section crm-error-message">Stripe.js token was not passed! Report this message to the site administrator.</div> <p><a href="http://www.site.org/" title="Main Menu">Return to home page.</a></p> </div> </div> <script language="JavaScript"> function toggle( element ) { var className = element.className; if ( className == 'crm-accordion-wrapper collapsed crm-fatal-error-details-block') { element.className = 'crm-accordion-wrapper crm-fatal-error-details-block'; } else { element.className = 'crm-accordion-wrapper collapsed crm-fatal-error-details-block'; } } </script>

**Comment by richardsplayground** [comment]
Just got this error with a version of the stripe plugin downloaded today from GitHub on a freshly upgraded CiviCRM version 4.7.1 on Drupal.  When looking at the JavaScript console during a test event registration/payment, I saw this:

> Navigated to https://site/civicrm/event/register?reset=1&action=preview&id=38
> register?reset=1&action=preview&id=38:1 
> Mixed Content: The page at 'https://site/civicrm/event/register?reset=1&action=preview&id=38' was loaded over HTTPS, but requested an insecure script 'http://site/sites/default/files/civicrm/extensions/com.drastikbydesign.stripe-4.6-dev/js/civicrm_stripe.js?r=lTa5i'. This request has been blocked; the content must be served over HTTPS.

Turns out my Resource URLs setting got munged during the CiviCRM Stripe extension upgrade and no longer pointed to https but was instead pointing to http.  Going to Administer->System Settings->Resource URLs and putting in https fixed the problem.

PS: In my case the value input in the GUI is overridden by a value stored in civicrm.settings.php, so if you are trying to put in https in the GUI over and over and it won't save, check civicrm.settings.php to see if there is an override in there.

**Comment by aydun** [comment]
I'm also getting the 'Stripe.js token was not passed!' message on a webform.  (Stripe is working in test mode from contribution pages.)  This is on two different webforms: one just a contribution, the other a membership.  It seems that civicrm_stripe.js is not getting loaded on the billing page. 

What/when/how should cause civicrm_stripe.js to be loaded?  

When the contribution page snippet is fetched, the stripe_add_stripe_js is called but there is no reference to the civicrm_stripe.js in what comes back.

This is stripe 4.6-dev latest github, webform 7.x-4.12, webform_civicrm 7.x-14, civicrm 4.6.14

**Comment by jmcclelland** [comment]
You might trying pulling in the commit I reference on this issue:

https://github.com/drastik/com.drastikbydesign.stripe/issues/113

Then add:
`
define('STRIPE_SUBMISSION_METHOD', 'php');

`To your civicrm.settings.php file

I don't know how it will ever be possible to figure out all the corner cases in CiviCRM forms to ensure we know when to add the right javascript :(.

Maybe with CiviCRM 5.0 comes out and we have a more sane forms layer.

**Comment by aydun** [comment]
@jmcclelland - thanks, that's a useful option.  I'd like to keep to the javscript method if possible for the security reasons you reference.    

As a workaround/gross-ugly-hack, I've added a markup box on the webform to load civicrm_stripe.js  Since others seems to have had success previously presumably the js must have been loaded and I hoping someone will explain how!

Also, since webform loads the billing block (which includes the stripe-pub-key) when needed, the stripe-pub-key is not present when the js is loaded, so the setPublishableKey call fails in document.ready, but moving that into the submit function works since the billing block is loaded by then.   It's not extensively tested, but works so far.

**Comment by laryn** [comment]
@aydun I am having the same issue on a webform. Core contrib pages function.

**Comment by madurak** [comment]
@aydun 
I have tried adding a markup component through the webform UI. But still get the Stripe.js error (>A fatal error was triggered: Stripe.js token was not passed! Report this message to the site administrator)

My test environment is:
Drupal: 7.50
CiviCRM: 4.6.21
Webform: 7.x-4.14
Webform CiviCRM: https://github.com/colemanw/webform_civicrm > branch 7.x-4.x
Stripe: https://github.com/drastik/com.drastikbydesign.stripe >branch: 4.6-dev (commit: d24d0cb)

-madu

**Comment by nishant-bhorodia** [comment]
Thanks @aydun, Your solutions works.
But this change needs to be done manually on every webform that uses stripe. So I override the BillingBlock.tpl and added civicrm_stripe.js to it manually. which works too!!

But is overriding a template an acceptable solution ?

Many Thanks!!

**Comment by aydun** [comment]
Hi @nishant-bhorodia - glad to hear that works for you too, but it's hardly a 'solution'!  My workaround adds civicrm_stripe.js manually to each webform but that should not be needed.  I'm not clear which part of the webform/stripe combination should be loading civicrm_stripe.js.  I have not looked at recent changes to this module so my comments are based on code as of March.

**Comment by nishant-bhorodia** [comment]
Thanks @aydun 
I am using the latest 4.6-dev branch and the civicrm_stripe.js issue is still there. I can think of two solutions at the moment:
1. Use hook_civicrm_alterContent to embed the civicrm_stripe.js in template.
2. Introduce a drupal module and use drupal_add_js to add the js to webform.
I think webform_civicrm doesn't fetch js from the civicrm extension.

**Comment by drastik** [comment]
It looks like https://github.com/drastik/com.drastikbydesign.stripe/pull/159 may fix this.

Just a few notes over there before committing.  Can anyone test that PR and provide feedback?

**Comment by adam-devapp** [comment]
May wish to check the comments I've posted here too:
https://github.com/drastik/com.drastikbydesign.stripe/issues/179

Found the class name had changed, and no token was generated. The JS posts the CC to stripe to get a token to use in the confirmation form. This token was blank because the class had changed, hence the error.

**Comment by onefiftyfour** [comment]
I'm confused about the activity on this issue.  Has anyone confirmed that this is fixed?

**Comment by lunarstack1** [comment]
Issue still exists for me.

After debugging the issue, I found when using an alternate branch the Javascript referred to a class which was incorrect - As a result, the stripe-token form field doesn't get generated and attached to the form, and this ultimately produces the message. The latest dev branch has this fix for the class, by adds the javascript and form field using an AJAX call. This seems not work without error. So the javascript is added to the form on initial load now and this seems to solve the issue. On the confirm page, click View Source Code in your browser and check stripe-token has a value for the input field. If you're quick enough, on post you can see the javascript code post to Stripe to concert the CC into a token for use by the form.

    if ($formName == "CRM_Contribute_Form_Contribution_Main") {
        CRM_Core_Resources::singleton()->addScriptFile('com.drastikbydesign.stripe', 'js/civicrm_stripe.js', 1);
        // Add some hidden fields for Stripe.
        if (!$form->elementExists('stripe_token')) {
            $stripe_token = (empty($params['stripe_token']) ? NULL : $params['stripe_token']);
            $form->setAttribute('class', $form->getAttribute('class') . ' stripe-payment-form');
            $form->addElement('hidden', 'stripe_token', $stripe_token, array('id' => 'stripe-token'));
        }
    }

**Comment by h-c-c** [comment]
@adam-devapp is this involving webforms?  If so, this commit b81d7fb should address it...and could you test?

@nishant-bhorodia I stole your idea to use hook_civicrm_alterContent...thanks!

**Comment by onefiftyfour** [comment]
(I'm on wordpress, I assume webforms is a Drupal thing?)

I just upgraded to the latest 4.7-dev.

With this latest version, I'm getting this error when I enable the pay later option. I don't get the error with the pay later option disabled.  

(CiviCRM 4.6.26)

**Comment by onefiftyfour** [comment]
I want to clarify that the Pay Later box doesn't have to be checked to get the error.  If the end user has the option to pay later, but does not check that box, the error will occur and no payment will be made.

If I remove the option to pay later - no error.

**Comment by drastik** [comment]
@onefiftyfour Yes, Webform = Drupal optional add on.

I heard in another ticket that the class of the payment form changed in CiviCRM.
Rather than change our class target again to keep up, I'd like to see a much more reliable approach achieved.  Originally, I used a hook to add a class to the payment form, but that also quit working...

**Comment by h-c-c** [comment]
Thanks for the clarification @onefiftyfour!  

@drastik I agree, a more reliable way is more desirable.  But until we find it, let's keep chasing, just so nobody is left out of the pay-processing fun.  :-)  FWIW, the class name is consistent between 4.6 and 4.7.  

@onefiftyfour  can you try the latest?   This ab35f709d74f0fd12fa435706999ae652424d7ef _should_ fix....although it's not the ultimate solution as mentioned.

**Comment by onefiftyfour** [comment]
My input names are "payment_processor" not "payment_processor_id" as referenced in civicrm_stripe.js. I made those changes in my civicrm_stripe.js and now it is working.

```
              <input value="17" type="radio" id="CIVICRM_QFID_17_payment_processor" name="payment_processor" checked="checked" class="crm-form-radio" />
               <input value="0" type="radio" id="CIVICRM_QFID_0_payment_processor" name="payment_processor" class="crm-form-radio" />
    
```

**Comment by h-c-c** [comment]
Nice....as it should.  @drastik As far as I can tell, this is the only 4.7 specific code that has been introduced.   Seems like not enough reason to revive 4.6-dev, right?  

I've tested the current with 1b664d15028f12b668962433965ef4d9d2277026 using:

4.6 and 4.7 with/without multiple payment options and each using webforms.

**Comment by arborrow** [comment]
FYI - I am still seeing the ever-persistent " Stripe.js token was not passed!  Report this message to the site administrator." issue on a Drupal 7.54, CiviCRM 4.7.17, Stripe 4.7-dev (as of March 7) - I will pull the latest commits and see if it persists and then work to gather more information as it is failing on some events but not others.

**Comment by lunarstack1** [comment]
Did a form class name change somewhere between CiviCRM versions? 

Can a form class name be injected into the template, so it is always present and the states in the JS can be relied upon. I found when the javascript class didn't exist in the HTML, then the token is never added as a form field, and then shows not found. Further, if there are other JS errors, then stripe never runs, because it is appended later in the process.

Perhaps try injecting the class using the alter method?

civicrm_alterTemplateFile($formName, &$form, $context, &$tplName)
{
    if ($formName == "CRM_Contribute_Form_Contribution_Main") {

    }

**Comment by arborrow** [comment]
I was looking at: http://civicrm.stackexchange.com/questions/16210/stripe-js-token-was-not-passed-using-webform-integration and wondering if there might still be an issue with webform.

Thanks Adam for your suggestion although I am not clear on where I would add that code. I am not all that familiar with CiviCRM and Stripe's integration. 

I am seeing the errors on the production site (in the logs) but have not had a chance to try to re-create them so that I can inspect what is loaded or not but I will do some digging and post back what I find.

**Comment by arborrow** [comment]
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:5
ajax @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:5
m._evalUrl @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:5
domManip @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:4
append @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:4
(anonymous) @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:4
m.access @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:4
html @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:4
(anonymous) @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:2265
j @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:2
fireWith @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:2
x @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:5
b @ js_8jGtDqbinvUNTzCmo9ER8RyDijBcX1WaRMjbGa6czR4.js:5

?_=1489457663261:2 It looks like Stripe.js was loaded more than one time. Please only load it once per page.

**Comment by h-c-c** [comment]
@arborrow can you update to the latest 4.7-dev? That should resolve the double loading and most likely the token not passed issue.   

 If not, I put in a handy js debug mode to help track down those problems.  If you do still see token not passed, please uncomment this line:
https://github.com/drastik/com.drastikbydesign.stripe/blob/4.7-dev/js/civicrm_stripe.js#L230

You'll see an error code in your browser console.

**Comment by arborrow** [comment]
Thanks, I have just updated to the latest 4.7-dev and when I tested the page in question it went through just fine. I have yet to be able to replicate the issue myself but others have experienced trouble so I will keep monitoring to see if it pops up again and if so I will enable the console log as you suggest.

**Comment by arborrow** [comment]
I have also disabled Drupal's performance option to aggregate js files just in case that may have been excluding something.

**Comment by h-c-c** [comment]
Thanks, glad to hear it's working for you.  I did some pretty exhaustive testing before pushing 38621a9.

**Comment by arborrow** [comment]
So I had another person have the issue and I was able to work a bit with them. We are using CiviDiscount (3.3) and when I applied the discount I get the stripe.js problem; however, without the discount the transaction went through. FYI, when using the discount code, I did not see any debugging in the console even though I had uncommented that line.

**Comment by arborrow** [comment]
Also, on the Stripe.com side of things, what is the best API to be using. The Readme indicates to use the latest but says at least the 12/13/2013 version. Is it recommended to upgrade to the latest (presumably 2/14/2017)?

**Comment by h-c-c** [comment]
@arborrow I would not mess with your Stripe API version at all unless you are on older than the recommended minimum.  If you investigate the API changes and find a good reason to change, then that's another story.  But I think anything else would be complicating any existing problems.  Personally I have 2015-10-16 in my dev account. 

> So I had another person have the issue and I was able to work a bit with them. We are using CiviDiscount (3.3) and when I applied the discount I get the stripe.js problem; however, without the discount the transaction went through. FYI, when using the discount code, I did not see any debugging in the console even though I had uncommented that line.

Are you saying that you only get debugging messages when you're not using a discount?  Or that you never see any console log messages?  Also, please make sure you've checked the "Preserve log" checkbox in Chrome. 

If you're not seeing the debug messages, that needs addressing first.  For good measure, I'd clear your drupal and civi caches.  

If you do see debug messages,can you be more specific about the situation?   Please tell me a story about how to reproduce this issue.  What kind of contribution page was it?  Were you using price sets?

**Comment by h-c-c** [comment]
@arborrow I see what you mean about the readme saying use the latest version of the api.  I think it's important to put that in the context of when that was written....apparently when version 1.8 came out.

**Comment by arborrow** [comment]
I will leave the stripe api where it is (12/13/2013). 

In the case of the stripe.js error message. I was seeing that when the event had a discount and the user applies the discount. I vaguely remember reading somewhere that when the page reloads that perhaps stripe.js was not getting loaded properly. 

In that scenario, despite having uncommented the debugging line to show an error on the console I was not receiving any js errors. That makes sense if in fact after applying the discount that civicrm_stripe.js is not getting re-loaded which is what seems to be happening. I am not sure how to ensure that the civicrm_stripe.js file is loaded after hitting apply and whether this would be considered a stripe or cividiscount issue. 

I am thinking it may be best to create a separate issue so that this issue can be resolved and closed. Any suggestions?

**Comment by h-c-c** [comment]
It's easy to tell if civicrm_stripe.js and stripe.js are loaded. Check in the sources tab of dev tools in Chrome.  You should be seeing the files loaded like in this screenshot. 

![screen shot 2017-03-18 at 12 00 21 am](https://cloud.githubusercontent.com/assets/5252344/24068858/bc877538-0b6f-11e7-825d-87642e1006e6.png)

I'm not convinced it's loading at all since it doesn't sound like _any_ debug messages are showing up in the console.  The debugging helper doesn't really provide error messages, it's more about being verbose about what is being executed. It's useful because we're interested in what it was doing when something unexpected happens.  With the line uncommented, you should _always_ be seeing messages like "'debug: ywkvh (Getting Stripe token)" when the Continue button is pressed.  This is what your console should look like after a valid discount is applied and the continue button is pressed:

![screen shot 2017-03-18 at 12 21 08 am](https://cloud.githubusercontent.com/assets/5252344/24068919/fad68a58-0b70-11e7-99ff-7d61002ffe69.png)

I remember that you had the js aggregation feature on at some point.  It's important to have that off and clear your drupal cache so that you can be sure you're using the debug mode. I'd go ahead and clear your extension and browser cache for good measure.   

I wouldn't bother with a new issue at this point.  I get the feeling think there is something very basic going wrong here.

**Comment by arborrow** [comment]
Thanks for the follow up. I have Drupal's js aggregation off, cache's cleared, etc. The civicrm_stripe.js file loads when the person goes to register the event; however, after entering a discount code and hitting apply it is not loaded (and hence no console messages). I am attaching 2 screenshots (pre-apply and post-apply). Thanks for any suggestions about next steps. 
Before apply:
![isi-prediscount](https://cloud.githubusercontent.com/assets/532371/24111639/204baafc-0d65-11e7-8a2b-d4aa4ab9cfce.png)
After apply:
![isi-post-apply-discount](https://cloud.githubusercontent.com/assets/532371/24111638/20490c0c-0d65-11e7-9dd2-0b2bc1ac3c5d.png)

**Comment by h-c-c** [comment]
@arborrow Thanks for the screenshots.  I can see now that your are using an event page with price sets.  

About the second screenshot, this is normal.  Our civicrm_stripe.js and stripe.js will not be loaded until you choose the 'credit card' option (assuming this is Stripe of course).  

Why don't you ping me on Mattermost (peter).

So far I can't reproduce this issue. I may need more detailed information on how you set up this page.

**Comment by h-c-c** [comment]
Hey @arborrow is this still an issue for you?  

If so, can you continue on from your last screenshot and select 'credit card' from the payment methods and confirm that civicrm_stripe.js and stripe.js are loaded?   Thanks!

**Comment by arborrow** [comment]
@h-c-c  Peter, my apologies for not following up. Yes, it is still an issue and no the js files were not loading after applying the discount. I have been tied up with non-tech work but will try to track down what may be happening and ping you on Mattermost if I cannot find anything. Peace - Anthony

**Comment by h-c-c** [comment]
Ok go ahead and ping me there.
> and no the js files were not loading after applying the discount.

 Just to be clear, this is not strictly what I was asking you to confirm. The js files should definitely _not_ be loaded at the point that you took the screenshot. 

Let me explain.  Because you have Pay Later turned on, you must select the 'credit card' option first (as you have it named in in your contribution page).   Then, and only then, can you make the judgment that there is an issue with js files not loading.

**Comment by arborrow** [comment]
![isi-w-cc](https://cloud.githubusercontent.com/assets/532371/24566911/119e0634-1621-11e7-956d-bac2c011af87.png)

Yes, even after selecting credit card there is still no js file.

**Comment by arborrow** [comment]
Strange behavior - I tried it again, closing the browser and starting over again
![isi-w-cc2](https://cloud.githubusercontent.com/assets/532371/24567366/fd888b68-1622-11e7-9970-682fa2be376a.png)

**Comment by h-c-c** [comment]
I was assuming you would have reloaded the page after clearing the browser cache....maybe that wasn't done? 

Just in case you missed this recommendation, can you confirm you cleared your Civi cache, and drupal cache?  It looks like you're running old code....it's very likely clearing your caches will solve your issue.


If not please confirm the following.

Running md5sum on stripe.php (in the top level extension) should yield:

de776afcd5b26215d4e9de21cb4c08c9  stripe.php

And running md5sum on  CRM/Core/Payment/Stripe.php should yield:

163a3e5a170bca204275ef3260517aff  CRM/Core/Payment/Stripe.php

**Comment by h-c-c** [comment]
I have news! 

I can replicate the "stripe.js already loaded" error by toggling from pay-later back to Stripe (in your page "credit card" and "check".  This isn't a show stopper.  So, sorry, I may be wrong about your Drupal and Civi cache being part of the issue.  Can't hurt to clear them anyway. 

But lo!  I found a way to reproduce the error and have a workaround.  In the payment processors config, can you set Stripe as your default payment processor?  Give that a test....

I see that if the discount is applied without a pay processor selected, I get "stripe.js token was not passed" also.

**Comment by arborrow** [comment]
Stripe is the only payment processor on this site and it was already checked as the default. I did notice that none of the Credit card types (MC, Visa, Discover, AmEx) were checked so I went ahead and checked and saved that. It will be a few days before I can get back to do more testing. Thanks for your help with this issue - much appreciated!

**Comment by h-c-c** [comment]
Oh, not having any card types selected in the pay processor config would cause problems, no doubt.  It would appear that this condition expresses itself also as overriding the default card setting.   

By having Stripe set as your default pay processor, the radio button for "credit card"  on your page should be selected by default when the page is loaded.  I can see in your screenshot that it is not.  Stripe is effectively not set as the default pay processor. 

![screen shot 2017-04-01 at 12 46 22 pm](https://cloud.githubusercontent.com/assets/5252344/24580792/a484c454-16dc-11e7-80de-d6562dff3a38.png)

**Comment by arborrow** [comment]
OK, So I am finally able to turn my attention back to this issue. My most recent testing has been that I am now not able to reproduce this issue. That said, I am not able to get Credit Card to be automagically selected either despite the fact that it is the default (and only) payment processor on our site but that is a separate issue. Peace - Anthony

**Comment by peoute** [comment]
I've been following this thread for several months now. @h-c-c thanks for your work on this! I tried the latest 4.7-dev and I think it solved the problem of having more than one form of payment along with Stripe.

I did run in to another issue, though. If Stripe is the only form of payment, and someone uses a 100% discount code (CiviDiscount), I get an error because Stripe expects payment info and of course the user isn't putting it in for $0.

**Comment by h-c-c** [comment]
Thanks for the thanks, @peoute!   And thanks for the report!  I can reproduce this error.   Wow, this beast needs e2e (end to end) unit tests so badly, to cover the many combinations and permutations of use cases.  

Also, I would have started a new issue for this since the actual error message doesn't at all resemble "Stripe.js token was not passed".  

A good issue title might be something like:  "Contribution fails with 100% discount and only Stripe"

**Comment by torrance** [comment]
We encountered this error on a contribution page (eg. civicrm/contribute/transact?id=543545) where there was also an unrelated webform in the sidebar. Both forms appear to have had stripe attached to them, but of course this caused an error where Stripe died since it could not be attached more than once. The result was the stripe-token was not populated and the user-facing error was the cryptic  'Stripe.js token not passed'.

**Comment by mattwire** [comment]
If you are still having trouble with stripe.js not passed please try my branch which fixes all known instances of this issue: https://github.com/mattwire/com.drastikbydesign.stripe/tree/4.7-mjwconsulting-dev-squashed

If using with drupal webform_civicrm you also need to apply https://github.com/colemanw/webform_civicrm/pull/100

**Comment by herbdool** [comment]
@mattwire in your fork have you considered modal forms when viewing a contact (e.g. /civicrm/contact/view?reset=1&cid=31761)? The civicrm-stripe.js file doesn't get loaded because there's no payment processor available until someone clicks to add a membership/contribution.

**Comment by mattwire** [comment]
@herbdool I don't think I understand... You can use stripe with any of the backend "submit credit card payment" contribution functions for event, membership and contribution.  Is there some other way you are trying to make a payment?

**Comment by herbdool** [comment]
@mattwire now that I've tested our patches again against 4.7.3 https://github.com/drastik/com.drastikbydesign.stripe/pull/219#issuecomment-392621109 I'm not having a problem with the modals.

For the record, by modal here I mean that by default clicking "Submit credit card payment" will have a popup modal. And this is configurable in Civi settings so that you can also have it refresh for the form instead of showing the form in a modal. In my original testing it was working in the latter but not the former.

**Comment by mattwire** [comment]
@herbdool So I think that the "modals" work fine in my branch - did you find otherwise?

**Comment by herbdool** [comment]
@mattwire like I said above, I initially had problems but with our patches (as listed in the other thread) worked. Can't confirm with your current fork.

We were trying to stay on the main extension but see what we could patch. You seem to have put a lot of work into your fork but too bad we haven't reconciled the two.

**Comment by hair-transplant** [comment]
is anyone running it on Joomla 3.8.8 / CiviCRM 5.1.2. ?
Tested 5.x.zip but also 4.7-mjwconsulting-dev-squashed
`Jun 03 22:11:04  [info] ALERT! Unmasked credit card received in back end. Please report this error to the site administrator.

Jun 03 22:11:05  [info] Stripe_Error create_customer:  <pre> Array
(
    [error] => Array
        (
            [code] => resource_missing
            [doc_url] => https://stripe.com/docs/error-codes/resource-missing
            [message] => No such token: Stripe Token
            [param] => card
            [type] => invalid_request_error
        )

)`
Also posted this in main thread under https://github.com/drastik/com.drastikbydesign.stripe/issues/255, but had (wrong) hopes that the modified 4.7. helps   
Error message is same.

**Comment by mattwire** [comment]
@hair-transplant Can you test the wordpress-dev branch of my fork: https://github.com/mattwire/com.drastikbydesign.stripe/tree/wordpress_dev - I've added a couple of fixes for wordpress, which may also fix the Joomla issues you were having.

**Comment by hair-transplant** [comment]
Took the fork and updated the following files:
Stripe.php
CRM/Core/Payment/Stripe.php
js/civicrm_strip.js

Did use test credit data from Stripe

Error message:
Error Oops! Looks like there was an error. Payment Response: 
Type: invalid_request_error
Code: resource_missing
Message: No such token: Stripe Token

Logfile:
Jun 30 09:39:02  [info] Stripe_Error save:  <pre> Array
(
    [error] => Array
        (
            [code] => resource_missing
            [doc_url] => https://stripe.com/docs/error-codes/resource-missing
            [message] => No such token: Stripe Token
            [param] => card
            [type] => invalid_request_error
        )
)
 </pre>

One more thing: 
In life mode Stripe for the membership module is working fine !
Its just the events module where the error occurs, which is really annoying as there is not one single registration which does not end with an error

**Comment by mattwire** [comment]
@hair-transplant Please can you paste a copy of all the debug that is printed in your browser console when you submit a payment and it fails?  That will tell us where it is failing.

Also, be REALLY sure that your browser is not using a cached version of any files (eg. civicrm_stripe.js)

**Comment by hair-transplant** [comment]
Okay, so I did log the console

a) with code from 5.x.zip
`VM1205 civicrm_stripe.js:347 civicrm_stripe.js: clearing submit-dont-process
VM1205 civicrm_stripe.js:347 civicrm_stripe.js: submit handler
VM1205 civicrm_stripe.js:347 civicrm_stripe.js: Not a Stripe transaction, or pay-later
VM1226:347 civicrm_stripe.js: clearing submit-dont-process
VM1226:347 civicrm_stripe.js: submit handler
VM1226:347 civicrm_stripe.js: Not a Stripe transaction, or pay-later
VM1227:347 civicrm_stripe.js: clearing submit-dont-process
VM1227:347 civicrm_stripe.js: submit handler
VM1227:347 civicrm_stripe.js: Not a Stripe transaction, or pay-later
Navigated to https://www.XXXXXX.com/index.php?option=com_civicrm&task=civicrm/event/register&Itemid=599&_qf_Confirm_display=true&qfKey=1235002785af67be8c881138c126d54c_7014
VM1250 jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
VM1282 civicrm_stripe.js:347 civicrm_stripe.js: No billing form!
inner.html:1 XHR finished loading: POST "https://m.stripe.com/4".
(anonymous) @ inner.html:1
t.default @ inner.html:1
h @ inner.html:1
(anonymous) @ inner.html:1
(anonymous) @ inner.html:1
Promise.then (async)
t.default @ inner.html:1
t.p @ inner.html:1
(anonymous) @ inner.html:1
inner.html:1 XHR finished loading: POST "https://m.stripe.com/4".
(anonymous) @ inner.html:1
t.default @ inner.html:1
h @ inner.html:1
t.b @ inner.html:1
onMessage @ inner.html:1
Navigated to https://www.XXXXXX.com/index.php?option=com_civicrm&task=index.php&Itemid=599&option=com_civicrm&task=civicrm/event/register&Itemid=599&_qf_Main_display=1&qfKey=1235002785af67be8c881138c126d54c_7014
jquery-migrate.min.js?9dbb0e16052dcd826c94d75561822169:2 JQMIGRATE: Migrate is installed, version 1.4.1
index.php?option=com_civicrm&task=index.php&Itemid=599&option=com_civicrm&task=civicrm/event/register&Itemid=599&_qf_Main_display=1&qfKey=1235002785af67be8c881138c126d54c_7014:737 GET https://www.XXXXXX.com/components/com_civicrm/civicrm/i/icons/jquery-ui-52534D.png 404 (Not Found)
?_=1530387587732:2 It looks like Stripe.js was loaded more than one time. Please only load it once per page.
(anonymous) @ ?_=1530387587732:2
(anonymous) @ ?_=1530387587732:2
`
b) with the changes done in wordpress
Used different browser to exclude cache problem
Now script was not running to the end, Apache 500 error
`JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:542
It looks like Stripe.js was loaded more than one time. Please only load it once per page. v2:2:7256
2018-06-30T19:53:51.717Z civicrm_stripe.js: clearing submit-dont-process civicrm_stripe.js:363:5
2018-06-30T19:53:51.719Z civicrm_stripe.js: submit handler civicrm_stripe.js:363:5
2018-06-30T19:53:51.720Z civicrm_stripe.js: Stripe is the selected payprocessor civicrm_stripe.js:363:5
2018-06-30T19:53:51.762Z civicrm_stripe.js: Created Stripe token civicrm_stripe.js:363:5
Gewechselt zu https://www.XXXXXX.com/index.php?option=com_civicrm&task=civicrm/event/register&Itemid=599
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:542
2018-06-30T19:53:54.978Z civicrm_stripe.js: No billing form! civicrm_stripe.js:363:5
Gewechselt zu https://www.XXXXXX.com/index.php?option=com_civicrm&task=civicrm/event/register&Itemid=599`

Couple of issues can be seen. Seems to be related to the event manager module, but difficult for me to interprete.

**Comment by mattwire** [comment]
@hair-transplant Thanks for the console log.  That's exactly what I need.  I will take a look at this in the next few days and get back to you hopefully with a fix.
Can you tell me what payment processors you have enabled on the registration page?  Only Stripe, or you have others as well?

**Comment by hair-transplant** [comment]
Its STRIPE "live key", Paypal , Stripe "test key" and "Pay later" option. 
I did test just STRIPE in the past , but as this did not change the situation I had to add other options.
Again, for "Membership" its working fine, its just the event page which is not running !

**Comment by mattwire** [comment]
@hair-transplant Please can you test the latest release 5.0.beta3 here: https://github.com/mattwire/com.drastikbydesign.stripe/releases/tag/5.0.beta3

I haven't specifically tried to fix your issue yet, but I did test on Joomla with contribution pages and that was working.  If it still does not work for Joomla event pages let me know and I will look in more detail.

**Comment by BorislavZlatanov** [comment]
Hi guys, I was getting the `Type: invalid_request_error
Code: resource_missing No such token: Stripe Token` error on a WordPress site. Moving the extension to the new location for extensions on Wordpress seems to have fixed this.

Old location: /wp-content/plugins/files/civicrm/ext
New location: /wp-content/uploads/civicrm/ext

Putting it out there in case it helps others. 

The extensions directory can be changed from Administer > System Settings > Directories.

**Comment by yorkshirerose** [comment]
> 
> 
> Hi guys, I was getting the `Type: invalid_request_error Code: resource_missing No such token: Stripe Token` error on a WordPress site. Moving the extension to the new location for extensions on Wordpress seems to have fixed this.
> 
> Old location: /wp-content/plugins/files/civicrm/ext
> New location: /wp-content/uploads/civicrm/ext
> 
> Putting it out there in case it helps others.
> 
> The extensions directory can be changed from Administer > System Settings > Directories.

Having similar issue - the extensions directory was already in your 'new' location but found some instructions on a different branch that helped:

Your CiviCRM 'Resource URLs' must be set to the extensions directory
relative to Drupal/CRM base. Example: /sites/all/civicrm_extensions/
NOT the full server path like /var/www/sites/all/civicrm_extensions/
The admin page for Resource URLs is: /civicrm/admin/setting/url

This fixed it for me.

**Comment by mwoodward-atd** [comment]
Thanks for these ideas -- I also already have the extensions in the new location (which is where they've always been for me), but I have two Stripe payment processors configured and I'm getting the resource missing error on one, but not the other.

I'm attaching a screenshot of my settings -- the top "CiviCRM Resource URL" setting is set in a config file from back when I migrated things from a dev site to a production instance (just deleted the site URL). If I open up the help is tells me these are the expanded values:
[cms.root] (my URL)
[civicrm.root] {my url}/wp-content/plugins/civicrm/civicrm/
[civicrm.files] {my url}/wp-content/uploads/civicrm/

When I try to submit something from the CiviCRM admin using the payment processor that doesn't work, I get redirected to a 404:
[my site]/wp-admin/action=add&cid=2&mode=live

Here's the error in the CiviCRM logs:
Dec 12 21:05:57  [debug] Stripe Payment Error: Payment Response: <br />Type: invalid_request_error<br />Code: resource_missing<br />Message: No such token: [token here]<br />

And here's the error I see on the Stripe side when I try to run a contribution through the payment processor that isn't working:
Request POST body
{
  "description": "Matt Woodward (CiviCRM)",
  "card": "[token here]",
  "email": "[my email]",
  "metadata": {
    "civicrm_contact_id": "2"
  }
}

Response body
{
  "error": {
    "code": "resource_missing",
    "doc_url": "https://stripe.com/docs/error-codes/resource-missing",
    "message": "No such token: [token here]",
    "param": "card",
    "type": "invalid_request_error"
  }
}

For what it's worth I *did* have the webhook URL incorrect when I first started testing this second payment processor but I fixed that several days ago. Just throwing that out there in case something is cached somewhere and I need to clear something out.

I appreciate any ideas anyone has on this. Thanks!
![screen shot 2018-12-16 at 9 16 16 am](https://user-images.githubusercontent.com/16122396/50056828-251c5480-0117-11e9-9001-2e1e07972c20.png)

**Comment by yorkshirerose** [comment]
My resource url settings are slightly different (see screenshot) 

<img width="551" alt="untitled" src="https://user-images.githubusercontent.com/43925307/50057446-8a496780-0162-11e9-900b-0db8563617d8.png">

Does this help?

**Comment by mwoodward-atd** [comment]
Thanks for the suggestion -- changed to that and unfortunately same behavior. It didn't break the payment processor that works, but it didn't fix the one that doesn't.

**Comment by mwoodward-atd** [comment]
In my case the problem apparently was due to the fact that I was using an older Stripe API on the payment processor that wasn't working. Upgrading that fixed the token issue so now I just have a different issue to contend with that I think is related to the fact that I've been on alphas and betas of the Stripe extension as it's been getting updated. Thanks for all the help!

**Comment by mwoodward-atd** [comment]
Well, spoke too soon. I got a "DB error - already exists" error after upgrading the Stripe API, but once I removed my existing record from the civicrm_stripe_customers table I'm back to the no such token error and get routed to a 404 in WordPress after attempting to submit a contribution. I guess I'll triple-check everything between the payment processor that works and the one that doesn't.

**Comment by lunarstack1** [comment]
> Well, spoke too soon. I got a "DB error - already exists" error after upgrading the Stripe API, but once I removed my existing record from the civicrm_stripe_customers table I'm back to the no such token error and get routed to a 404 in WordPress after attempting to submit a contribution. I guess I'll triple-check everything between the payment processor that works and the one that doesn't.

With the newest CiviCRM version of the module https://lab.civicrm.org/extensions/stripe.git, I found after upgrading that I would receive a similar error. I fixed it by dropping the triggers associated with the civicrm_stripe_customers table, as the entry would create but the trigger would fail.

**Comment by mwoodward-atd** [comment]
Thanks! I'll look into that. So you just removed all the triggers associated with that table?
